steps:
  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-Dmaven.test.skip=true']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/concrete-crow-244606/spring-prometheus', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/concrete-crow-244606/spring-prometheus', '.']
    
images: ['gcr.io/concrete-crow-244606/spring-prometheus']
